### ISSUE TITLE
Method level parameters are missing when using Yaml generation utilities

### ISSUE THREAD

**Issue by krmahadevan** [cbeust/testng#1787]
### TestNG Version
> Note: only the latest version is supported

6.14.3

### Expected behavior
Method level parameters should be included in the Yaml file.

### Actual behavior
Method level parameters are currently missing.

### Is the issue reproductible on runner?

- [X] Shell
- [X] Maven
- [X] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

The xml being used

```xml
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="TEQ Test">
    <parameter name="suiteLevel" value="suiteValue"/>
    <test name="TeqInit Test">
        <parameter name="testLevel" value="testValue"/>
        <classes>
            <class name="rationale.emotions.yamlissue.IssueTest">
                <methods>
                    <include name="configureTeq">
                        <parameter name="teqUid" value="Teq1"/>
                    </include>
                    <include name="initTraffic">
                        <parameter name="teqUid" value="Teq2"/>
                    </include>
                    <include name="setProtSwitchCriteria">
                        <parameter name="teqUid" value="Teq3"/>
                    </include>
                </methods>
            </class>
        </classes>
    </test>
</suite>
```

Expected yaml file should have looked like below

```yaml
name: TEQ Test
configFailurePolicy: skip
parameters: { suiteLevel: suiteValue }
tests:
  - name: TeqInit Test
    parameters: { testLevel: testValue }
    classes:
      - name: rationale.emotions.yamlissue.IssueTest
        includedMethods:
          - name: configureTeq
            parameters: { teqUid: Teq1 }
          - name: initTraffic
            parameters: { teqUid: Teq2 }
          - name: setProtSwitchCriteria
            parameters: { teqUid: Teq3 }
```

Actual yaml file that is getting generated 

```yaml
name: TEQ Test
configFailurePolicy: skip
parameters: { suiteLevel: suiteValue }
tests:
  - name: TeqInit Test
    parameters: { testLevel: testValue }
    classes:
      - name: rationale.emotions.yamlissue.IssueTest
        includedMethods:
          - configureTeq
          - initTraffic
          - setProtSwitchCriteria
```

Sample test that can be used to reproduce the problem

```java
import org.testng.Assert;
import org.testng.annotations.Test;
import org.testng.internal.Yaml;
import org.testng.xml.SuiteXmlParser;
import org.testng.xml.XmlSuite;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class IssueTest {
  @Test
  public void testMethod() throws FileNotFoundException {
    SuiteXmlParser parser = new SuiteXmlParser();
    String file = "src/test/resources/yamlissue.xml";
    XmlSuite xmlSuite = parser.parse(file, new FileInputStream(file), false);
    StringBuilder yaml = org.testng.internal.Yaml.toYaml(xmlSuite);
    System.out.println(yaml);
    Matcher m = Pattern.compile("parameters:").matcher(yaml.toString());
    int count = 0;
    while (m.find()) {
      count++;
    }
    Assert.assertEquals(5, count);
  }
}

```
