### ISSUE TITLE
Chrome crashed when execute the selenium test cases on the bitbucket pipeline

### ISSUE THREAD

**Issue by MeghnaSc** [cbeust/testng#2681]
Please find the trace route which I get on bitbucket pipeline 

> org.openqa.selenium.WebDriverException: unknown error: Chrome failed to start: crashed.
>   (unknown error: DevToolsActivePort file doesn't exist)
>   (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

Please refer sample bitbucket-pipelines.xml file :

```yml
image: markhobson/maven-chrome:jdk-8

pipelines:
  default:
    - step:
        name: Automation Test
        caches:
          - maven
        script:
          - apt-get update
          - mvn clean test        
```

Whenever I run the pipeline, I am getting above error.

Also refer testng.xml file :

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Suite">

<listeners>

<listener class-name="testcases.Listeners"/>

</listeners>

  <test thread-count="3" name="Test" parallel="classes">
    <classes>
      <class name="testcases.Test1"/>      
    </classes>
  </test> <!-- Test -->
</suite> <!-- Suite -->
```

I am using surefire plugin like below :

```xml
<build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.0.0-M5</version>
        <configuration>
          <suiteXmlFiles>
            <suiteXmlFile>testng.xml</suiteXmlFile>
          </suiteXmlFiles>
        </configuration>
      </plugin>
    </plugins>
  </build>
```

Anyone can help me for this issue?

What is the best way to integrate bitbucket with selenium automation
